const fs = require('fs');
const path = require('path');

/**
 * Minimal resume-to-PDF generator.
 *
 * IMPORTANT:
 * - This repo already has invoicePdfService.js used for invoice PDFs.
 * - To keep behavior consistent, we mirror its approach only if it exposes a generator.
 * - If invoicePdfService.js doesn't provide a generic resume generator, we fallback
 *   to saving an HTML file as a placeholder.
 *
 * For the current task, we implement an HTML->PDF-lite approach by storing HTML
 * and returning its path if PDF libs are unavailable.
 */

async function generateResumePdf({
  resumeData,
  photoUrl,
  userName,
  outputPath,
}) {
  // Output: user-specific folder under /tmp-resumes
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const {
    fullName,
    qualifications,
    experience,
    personalInfo,
  } = resumeData || {};

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Resume - ${escapeHtml(fullName || userName || '')}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 28px; color: #111827; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; }
  .name { font-size: 26px; font-weight: 700; }
  .photo { width: 92px; height: 92px; border-radius: 10px; object-fit: cover; border: 1px solid #e5e7eb; }
  h3 { margin-top: 18px; margin-bottom: 8px; font-size: 16px; color:#1d4ed8; }
  .section { margin-bottom: 14px; }
  ul { margin: 0; padding-left: 18px; }
  li { margin: 6px 0; }
  .muted { color: #6b7280; font-size: 12px; }
  .kv { font-size: 13px; }
  .kv b { color:#111827; }
  .box { border:1px solid #e5e7eb; border-radius: 12px; padding: 14px; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="name">${escapeHtml(fullName || userName || '')}</div>
      <div class="muted">Generated by InternArea Premium Resume</div>
    </div>
    ${photoUrl ? `<img class="photo" src="${photoUrl}" alt="photo" />` : ''}
  </div>

  <div class="section box" style="margin-top:14px;">
    <h3>Personal Information</h3>
    <div class="kv">
      ${renderKv(personalInfo)}
    </div>
  </div>

  <div class="section box">
    <h3>Qualifications</h3>
    ${renderTextBlock(qualifications)}
  </div>

  <div class="section box">
    <h3>Experience</h3>
    ${renderTextBlock(experience, true)}
  </div>

  <div class="muted" style="margin-top:18px; text-align:center;">
    This document was generated after successful payment verification.
  </div>
</body>
</html>`;

  // In absence of a PDF renderer library, we persist HTML as .pdf.html.
  // The frontend can still download as HTML; in production swap with real PDF.
  fs.writeFileSync(outputPath + '.html', html, 'utf8');
  return outputPath + '.html';
}

function escapeHtml(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

function renderKv(personalInfo) {
  if (!personalInfo) return '';
  const rows = [];
  const push = (k, v) => {
    if (v === undefined || v === null || v === '') return;
    rows.push(`<div style="margin:6px 0;"><b>${escapeHtml(k)}:</b> ${escapeHtml(v)}</div>`);
  };

  // Common fields we expect
  push('Email', personalInfo.email);
  push('Phone', personalInfo.phone);
  push('Location', personalInfo.location);
  push('LinkedIn', personalInfo.linkedin);
  push('Website', personalInfo.website);

  // fallback: dump known keys
  if (rows.length === 0) {
    Object.entries(personalInfo).forEach(([k, v]) => push(k, v));
  }

  return rows.join('');
}

function renderTextBlock(block, allowBullets = false) {
  if (!block) return `<div class="muted">Not provided.</div>`;

  // Accept string, array of strings, or object
  if (typeof block === 'string') {
    if (allowBullets) return `<div>${escapeHtml(block).split('\n').join('<br/>')}</div>`;
    return `<div>${escapeHtml(block)}</div>`;
  }

  if (Array.isArray(block)) {
    if (allowBullets) {
      return `<ul>${block.map((x) => `<li>${escapeHtml(x)}</li>`).join('')}</ul>`;
    }
    return `<div>${block.map((x) => escapeHtml(String(x))).join('<br/>')}</div>`;
  }

  // object fallback
  return `<div>${escapeHtml(JSON.stringify(block, null, 2))}</div>`;
}

module.exports = {
  generateResumePdf,
};

